version: '3.8'

services:
  mongo-auth:
    image: mongo
    container_name: mongo-auth
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-user:
    image: mongo
    container_name: mongo-user
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-user-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-post:
    image: mongo
    container_name: mongo-post
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongo-post-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-message:
    image: mongo
    container_name: mongo-message
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - mongo-message-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-notification:
    image: mongo
    container_name: mongo-notification
    restart: unless-stopped
    ports:
      - "27021:27017"
    volumes:
      - mongo-notification-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # TODO services Node/Express 
volumes:
  mongo-auth-data:
  mongo-user-data:
  mongo-post-data:
  mongo-message-data:
  mongo-notification-data:

networks:
  app-network:
    driver: bridge
