version: '3.8'

services:
  nginx:
    image: nginx:latest     
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8080:8080" #Nous exposerons sur le port 8080
    networks:
      - app-network
    depends_on:
      - auth-service
      - post-service

  mongo-auth:
    image: mongo
    container_name: mongo-auth
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - app-network

  auth-service:
    build: ./Backend/auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo-auth
    networks:
      - app-network
    volumes:
      - ./Backend/auth-service/logs:/home/logs/auth-service

  mongo-post:
    image: mongo
    container_name: mongo-post
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-post-data:/data/db
    depends_on:
      - mongo-auth
      - auth-service
    networks:
      - app-network

  post-service:
    build: ./Backend/post-service
    container_name: post-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    depends_on:
      - mongo-post
    networks:
      - app-network
    volumes:
      - ./Backend/post-service/logs:/home/logs/post-service

volumes:
  mongo-auth-data:
  mongo-post-data:

networks:
  app-network:
    driver: bridge
