version: '3.8'

services:
  nginx:
    image: nginx:latest 
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080" #Nous exposerons sur le port 8080
    networks:
      - app-network
    depends_on:
      - auth-service

  mongo-auth:
    image: mongo
    container_name: mongo-auth
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - app-network

  auth-service:
    build: ./Backend/auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo-auth
    networks:
      - app-network

volumes:
  mongo-auth-data:

networks:
  app-network:
    driver: bridge
