version: '3.8'

services:
  nginx:
    image: nginx:latest     
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8080:8080" #Nous exposerons sur le port 8080
    networks:
      - app-network
    depends_on:
      - auth-service
      - post-service

  mongo-user:
    image: mongo
    container_name: mongo-user
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-user-data:/data/db
    networks:
      - app-network

  auth-service:
    build: ./Backend/auth-service
    container_name: auth-service
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - ACCESS_JWT_KEY=dazhbdajbdjadakd
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo-user
      - user-service
    networks:
      - app-network
    volumes:
      - ./Backend/auth-service/logs:/home/logs/auth-service

  mongo-post:
    image: mongo
    container_name: mongo-post
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-post-data:/data/db
    depends_on:
      - mongo-user
      - auth-service
    networks:
      - app-network

  post-service:
    build: ./Backend/post-service
    container_name: post-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    depends_on:
      - mongo-post
    networks:
      - app-network
    volumes:
      - ./Backend/post-service/logs:/home/logs/post-service

  user-service:
    build: ./Backend/user-service
    container_name: user-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./Backend/user-service/logs:/home/logs/user-service

volumes:
  mongo-user-data:
  mongo-post-data:

networks:
  app-network:
    driver: bridge
